// AUTO-GENERATED FROM skills/*.md — DO NOT EDIT BY HAND.
// Regenerated by scripts/build-skill-metadata.mjs (runs via predev / prebuild).
import type { SkillMeta } from './types';

export const skillMetadata: SkillMeta[] = [
  {
    "id": "expense-categorizer",
    "name": "Expense Categorizer",
    "description": "Parse raw expense descriptions into GL categories with confidence scores.",
    "icon": "🧾",
    "color": "emerald",
    "category": "Expense Management",
    "exampleInputs": [
      "Uber to airport $45, team lunch at Sweetgreen $230, AWS bill $1,240",
      "Hotel in Austin $612, conference ticket $899, client dinner $187",
      "Figma annual seat $180, Notion team $96, Adobe CC $54"
    ],
    "outputFormat": "Markdown table with columns: Description | Category | GL Code | Amount | Confidence",
    "chainableAfter": [
      "invoice-extractor"
    ]
  },
  {
    "id": "vendor-risk-flagger",
    "name": "Vendor Risk Flagger",
    "description": "Assess a vendor for risk signals: geography, industry, data sensitivity, freshness.",
    "icon": "🚩",
    "color": "rose",
    "category": "Risk",
    "exampleInputs": [
      "NovaCloud Ltd — payment processor based in Cyprus, signed up last week",
      "Acme Marketing LLC — agency we have used for 3 years, US-based",
      "Quanta Data Services — offshore data labeling vendor, handles PII"
    ],
    "outputFormat": "Risk level header, then a \"Flags\" bullet list, then a \"Reasoning\" paragraph, then \"Recommended action\"."
  },
  {
    "id": "invoice-extractor",
    "name": "Invoice Data Extractor",
    "description": "Pull structured fields out of pasted invoice text: vendor, totals, line items, terms.",
    "icon": "📄",
    "color": "sky",
    "category": "Operations",
    "exampleInputs": [
      "INVOICE #4421\nFrom: Globex Logistics\nDate: 2026-04-30\nFreight services Apr 1–30: $4,200\nFuel surcharge: $310\nTax: $360\nTotal: $4,870\nNet 30",
      "Bill To: Initech\nInvoice 22-A from Pied Piper Inc.\n2026-05-01\n- Compression services 100hr @ $150 = $15,000\n- Setup fee $2,500\nSubtotal $17,500 | Tax $1,575 | Total $19,075 | Due on receipt"
    ],
    "outputFormat": "Header section (vendor / invoice no / date / terms), a line-items markdown table, and a totals block."
  },
  {
    "id": "policy-compliance-checker",
    "name": "Policy Compliance Checker",
    "description": "Check an expense against company policy and surface which rules trigger.",
    "icon": "✅",
    "color": "violet",
    "category": "Compliance",
    "exampleInputs": [
      "Team dinner for 4 people, $520, client pitch celebration",
      "New SaaS subscription $1,200/mo for analytics tool, requested by IC",
      "Conference travel to Lisbon, $2,800, booked 2 days out"
    ],
    "outputFormat": "Compliant/Non-compliant header, list of triggered policies, suggested action.",
    "chainableAfter": [
      "invoice-extractor",
      "expense-categorizer"
    ]
  },
  {
    "id": "spend-anomaly-detector",
    "name": "Spend Anomaly Detector",
    "description": "Surface duplicates, weekend charges, round-number patterns, and unusual amounts.",
    "icon": "🔍",
    "color": "amber",
    "category": "Risk",
    "exampleInputs": [
      "date,vendor,amount\n2026-05-01,AWS,1240.55\n2026-05-01,AWS,1240.55\n2026-05-04,Sweetgreen,87.10\n2026-05-10,Delta Air,500.00\n2026-05-10,Delta Air,500.00",
      "Sat 2026-04-26 — Best Buy $1,499\nSun 2026-04-27 — Apple Store $2,000\nMon 2026-04-28 — Office Depot $42.15",
      "2026-03-15 Stripe Fees $312.44\n2026-03-15 Stripe Fees $312.44\n2026-03-22 Stripe Fees $407.18"
    ],
    "outputFormat": "Flagged-items table with anomaly type and severity, plus a short summary.",
    "chainableAfter": [
      "expense-categorizer"
    ]
  },
  {
    "id": "meeting-cost-calculator",
    "name": "Meeting Cost Calculator",
    "description": "Estimate the loaded-cost of a meeting and judge whether it was worth it.",
    "icon": "⏱️",
    "color": "fuchsia",
    "category": "Operations",
    "exampleInputs": [
      "8 attendees, 60 minutes, mix of mid and senior",
      "4 execs and 2 senior ICs, 90-minute strategy review",
      "12 juniors, 30 minutes, weekly status update"
    ],
    "outputFormat": "Summary block with total cost, cost/minute, per-person breakdown table, worth-it verdict.",
    "chainableAfter": [
      "vendor-risk-flagger"
    ]
  }
];

export function getSkillMetaById(id: string): SkillMeta | undefined {
  return skillMetadata.find((s) => s.id === id);
}
